feature(creating some unitary tests for the frontend)

diff --git a/frontend/Dockerfile.dev b/frontend/Dockerfile.dev
--- a/frontend/Dockerfile.dev
+++ b/frontend/Dockerfile.dev
@@ -4,10 +4,11 @@ WORKDIR /app
 
 RUN npm install -g npm
 
-COPY . .
-
+COPY package*.json ./
 RUN npm install
+
+COPY . .
 
 EXPOSE 5173
 
-CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
+CMD sh -c "npm run test || echo '⚠ Tests failed, check the output above'; npm run dev -- --host 0.0.0.0"
